name: Python CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-and-style-check:
    name: Lint and Style Check
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout Code
        uses: actions/checkout@v3

      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      
      - name: Run Flake8
        run: flake8 .
        env:
          MAX_LINE_LENGTH: 88 

      
      - name: Run Black
        run: black --check .


      - name: Run Pylint
        run: pylint $(find . -name "*.py")
        continue-on-error: false 

  build:
    name: Build and Test
    runs-on: ubuntu-latest
    needs: lint-and-style-check
    steps:
      
      - name: Checkout Code
        uses: actions/checkout@v3

      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      
      - name: Run Unit Tests
        run: |
          pytest --cov=.

    
      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
