name: Python CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint-and-build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run static code analysis (e.g., with Flake8 or pylint)
      - name: Run Flake8
        run: |
          pip install flake8
          flake8 .

      # Step 5: Run code style checks (e.g., with Black)
      - name: Run Black
        run: |
          pip install black
          black --check .

      # Step 6: Run tests
      - name: Run unit tests
        run: |
          pip install pytest
          pytest

      # Step 7: (Optional) Build the application
      - name: Build the application
        run: |
          echo "Building the application..."
          # Add your build commands here
